# Generated by Django 3.1.3 on 2024-09-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20240907_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='image3/', verbose_name='업로드 이미지3'),
        ),
    ]
