# Generated by Django 3.1.3 on 2024-09-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_question_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='image4/', verbose_name='업로드 이미지4'),
        ),
    ]
